onboarding = false
[theme]
name = "catppuccin"

[keys]
prefix = "ctrl+a"
navigate_workspace_up = "k"
navigate_workspace_down = "j"

[[keys.command]]
key = "ctrl+h"
type = "shell"
command = "~/.config/herdr/bin/navigator left ctrl+h"
description = "navigate left"

[[keys.command]]
key = "ctrl+j"
type = "shell"
command = "~/.config/herdr/bin/navigator down ctrl+j"
description = "navigate down"

[[keys.command]]
key = "ctrl+k"
type = "shell"
command = "~/.config/herdr/bin/navigator up ctrl+k"
description = "navigate up"

[[keys.command]]
key = "ctrl+l"
type = "shell"
command = "~/.config/herdr/bin/navigator right ctrl+l"
description = "navigate right"

[ui]
agent_panel_sort = "priority"
pane_borders = true
pane_gaps = false
show_agent_labels_on_pane_borders = false

[ui.sound]
enabled = false
