// Originally generated by moshi-hook; customized in dotfiles.
// Re-running `moshi-hook install --target pi` may overwrite this file.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent"
import { spawn } from "node:child_process"
import { existsSync } from "node:fs"

const helperCandidates = [
  process.env.MOSHI_HOOK_BIN,
  "/opt/homebrew/bin/moshi-hook",
  "/usr/local/bin/moshi-hook",
  "moshi-hook",
].filter((candidate): candidate is string => typeof candidate === "string" && candidate.length > 0)

function helperBinary(): string {
  return helperCandidates.find((candidate) => candidate.includes("/") && existsSync(candidate)) || helperCandidates[helperCandidates.length - 1]
}

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" ? (value as Record<string, unknown>) : undefined
}

function firstString(...values: unknown[]): string {
  for (const value of values) {
    if (typeof value === "string" && value.trim()) return value.trim()
  }
  return ""
}

function textFromContent(value: unknown): string {
  if (typeof value === "string") return value
  if (!Array.isArray(value)) return ""

  return value
    .map((chunk) => {
      if (typeof chunk === "string") return chunk
      if (chunk && typeof chunk === "object" && "text" in chunk) {
        const text = (chunk as { text?: unknown }).text
        return typeof text === "string" ? text : ""
      }
      return ""
    })
    .filter(Boolean)
    .join(" ")
}

function textFromMessage(value: unknown): string {
  const message = asRecord(value)
  if (!message) return ""

  return firstString(
    textFromContent(message.content),
    textFromContent((message.message as Record<string, unknown> | undefined)?.content),
    textFromContent((message.entry as Record<string, unknown> | undefined)?.content),
  )
}

function modelLabel(model: unknown): string {
  const obj = asRecord(model)
  if (!obj) return ""

  return firstString(
    obj.displayName,
    obj.display_name,
    obj.name,
    obj.id,
    obj.modelId,
  )
}

function sessionID(event: Record<string, unknown>, ctx: Record<string, unknown>): string {
  const sessionManager = ctx.sessionManager as Record<string, unknown> | undefined
  const getSessionFile = sessionManager?.getSessionFile
  let sessionFile = ""

  if (typeof getSessionFile === "function") {
    try {
      sessionFile = String(getSessionFile.call(sessionManager) ?? "")
    } catch {}
  }

  return firstString(
    event.session_id,
    event.sessionId,
    sessionFile,
    ctx.cwd,
    "pi",
  )
}

function send(eventName: string, event: unknown, ctx: unknown, extra: Record<string, unknown> = {}): void {
  const eventObj = asRecord(event) || {}
  const ctxObj = asRecord(ctx) || {}
  const payload = {
    hook_event_name: eventName,
    session_id: sessionID(eventObj, ctxObj),
    cwd: firstString(ctxObj.cwd, process.cwd()),
    model: modelLabel(ctxObj.model),
    event,
    ...extra,
  }

  try {
    const child = spawn(helperBinary(), ["pi-hook"], {
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
    })
    child.stdin.end(JSON.stringify(payload))
    child.unref()
  } catch {
    // Moshi lifecycle reporting must never interrupt a Pi turn.
  }
}

export default function moshiPiHook(pi: ExtensionAPI): void {
  pi.on("session_start", (event, ctx) => {
    send("SessionStart", event, ctx)
  })

  pi.on("before_agent_start", (event, ctx) => {
    send("UserPromptSubmit", event, ctx, { prompt: event.prompt })
  })

  pi.on("agent_start", (event, ctx) => {
    send("AgentStart", event, ctx)
  })

  pi.on("agent_end", (event, ctx) => {
    const messages = Array.isArray(event.messages) ? event.messages : []
    const lastMessage = messages.length > 0 ? messages[messages.length - 1] : undefined
    send("AgentEnd", event, ctx, { last_assistant_message: textFromMessage(lastMessage) })
  })
}
