name: Justfile Bootstrap Check

on:
  push:
    paths:
      - "Justfile"
  workflow_dispatch:

jobs:
  test-justfile:
    runs-on: macos-latest
    name: Check Boostrap Script
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Just
        run: brew install just

      - name: Install Casks
        run: just install-casks
